#Spring Configuration Properties
spring.config.import=optional:file:.env[.properties]
#Application Name
spring.application.name=student-management-api
#H2 Configuration
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=${H2_URL_KEY}
spring.datasource.username=${H2_USER_KEY}
spring.datasource.password=${H2_PASSWORD_KEY}
spring.jpa.hibernate.ddl-auto=update
#H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.open-in-view=true
spring.jpa.defer-datasource-initialization=true
#Swagger
springdoc.swagger-ui.path=/docs-students-management.html
springdoc.api-docs.path=/docs-students-management